apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage-claim
  namespace: app
spec:
  volumeName: file-storage
  storageClassName: manual
  accessModes:
    - ReadOnlyMany  # access mode 
  resources:
    requests:
      storage: 10Gi
